name: Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure Rclone
        run: |
          mkdir -p ~/.config/rclone/
          echo "${{ secrets.RCLONE}}" | base64 --decode > ~/.config/rclone/rclone.conf

      - name: Generate Test File
        run: python3 Script.py

      - name: Upload File to Google Drive
        run: rclone copy test_file.txt mashilo:/TestFolder --progress
